{% set name = "openamundsen" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openamundsen-{{ version }}.tar.gz
  sha256: 480ff169bb384b6fbf7a3952c7ccba1586e831216a5ecbb4610d3d7f9cd8dc05

build:
  number: 0
  noarch: python
  entry_points:
    - openamundsen = openamundsen.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.0
    - wheel
  run:
    - cerberus
    - importlib-metadata
    - loguru
    - munch
    - netcdf4
    - numba >=0.50.1
    - numpy
    - pandas >=1.1.0
    - pyproj
    - python >={{ python_min }}
    - rasterio >=1.1.0
    - ruamel.yaml >=0.15.0
    - scipy
    - setuptools-scm
    - xarray >=0.14.0

test:
  requires:
    - dask
    - pip
    - pooch
    - pytest
    - pvlib-python
    - python {{ python_min }}
  source_files:
    - ./tests
  imports:
    - openamundsen
  commands:
    - pip check
    - openamundsen --help
    - pytest

about:
  home: https://github.com/openamundsen/openamundsen
  summary: Modular snow and hydroclimatological modeling framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhanzer
